AWSTemplateFormatVersion: '2010-09-09'
Description: Real‑Time Fraud Ingestion Pipeline

Parameters:
  Stage:
    Type: String
    Default: dev

Resources:
  RawBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'raw-fraud-data-bucket-${Stage}'

  FraudKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub 'fraud-txn-stream-${Stage}'
      ShardCount: 1

  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'firehose-role-${Stage}'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FirehoseToS3
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt RawBucket.Arn
                  - !Sub '${RawBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - kinesis:DescribeStream
                  - kinesis:GetShardIterator
                  - kinesis:GetRecords
                Resource: !GetAtt FraudKinesisStream.Arn

  FraudFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Sub 'fraud-firehose-to-s3-${Stage}'
      DeliveryStreamType: KinesisStreamAsSource
      KinesisStreamSourceConfiguration:
        KinesisStreamARN: !GetAtt FraudKinesisStream.Arn
        RoleARN: !GetAtt FirehoseRole.Arn
      S3DestinationConfiguration:
        BucketARN: !GetAtt RawBucket.Arn
        RoleARN: !GetAtt FirehoseRole.Arn
        Prefix: 'raw-data/'
        BufferingHints:
          SizeInMBs: 5
          IntervalInSeconds: 60

Outputs:
  StreamName:
    Value: !Ref FraudKinesisStream
  BucketName:
    Value: !Ref RawBucket
  FirehoseName:
    Value: !Ref FraudFirehose
